/* Copyright 2019 Google LLC. All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/policycache.proto

package com.google.cloud.util.bpm;

/**
 * Protobuf type {@code google.protobuf.util.PolicyCache}
 */
public  final class PolicyCache extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.util.PolicyCache)
    PolicyCacheOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PolicyCache.newBuilder() to construct.
  private PolicyCache(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PolicyCache() {
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PolicyCache(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timestamp_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              bucket_ = com.google.protobuf.MapField.newMapField(
                  BucketDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
            bucket__ = input.readMessage(
                BucketDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            bucket_.getMutableMap().put(
                bucket__.getKey(), bucket__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetBucket();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.util.bpm.PolicyCache.class, com.google.cloud.util.bpm.PolicyCache.Builder.class);
  }

  public interface HashOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.util.PolicyCache.Hash)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>string sha256 = 2;</code>
     */
    java.lang.String getSha256();
    /**
     * <code>string sha256 = 2;</code>
     */
    com.google.protobuf.ByteString
        getSha256Bytes();
  }
  /**
   * Protobuf type {@code google.protobuf.util.PolicyCache.Hash}
   */
  public  static final class Hash extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.util.PolicyCache.Hash)
      HashOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hash.newBuilder() to construct.
    private Hash(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hash() {
      timestamp_ = 0L;
      sha256_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hash(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sha256_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_Hash_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_Hash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.util.bpm.PolicyCache.Hash.class, com.google.cloud.util.bpm.PolicyCache.Hash.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SHA256_FIELD_NUMBER = 2;
    private volatile java.lang.Object sha256_;
    /**
     * <code>string sha256 = 2;</code>
     */
    public java.lang.String getSha256() {
      java.lang.Object ref = sha256_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sha256_ = s;
        return s;
      }
    }
    /**
     * <code>string sha256 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSha256Bytes() {
      java.lang.Object ref = sha256_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sha256_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!getSha256Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sha256_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!getSha256Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sha256_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.cloud.util.bpm.PolicyCache.Hash)) {
        return super.equals(obj);
      }
      com.google.cloud.util.bpm.PolicyCache.Hash other = (com.google.cloud.util.bpm.PolicyCache.Hash) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getSha256()
          .equals(other.getSha256());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + SHA256_FIELD_NUMBER;
      hash = (53 * hash) + getSha256().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.util.bpm.PolicyCache.Hash parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.cloud.util.bpm.PolicyCache.Hash prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.util.PolicyCache.Hash}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.util.PolicyCache.Hash)
        com.google.cloud.util.bpm.PolicyCache.HashOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_Hash_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_Hash_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.util.bpm.PolicyCache.Hash.class, com.google.cloud.util.bpm.PolicyCache.Hash.Builder.class);
      }

      // Construct using com.google.cloud.util.bpm.PolicyCache.Hash.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        sha256_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_Hash_descriptor;
      }

      @java.lang.Override
      public com.google.cloud.util.bpm.PolicyCache.Hash getDefaultInstanceForType() {
        return com.google.cloud.util.bpm.PolicyCache.Hash.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.cloud.util.bpm.PolicyCache.Hash build() {
        com.google.cloud.util.bpm.PolicyCache.Hash result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.cloud.util.bpm.PolicyCache.Hash buildPartial() {
        com.google.cloud.util.bpm.PolicyCache.Hash result = new com.google.cloud.util.bpm.PolicyCache.Hash(this);
        result.timestamp_ = timestamp_;
        result.sha256_ = sha256_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.cloud.util.bpm.PolicyCache.Hash) {
          return mergeFrom((com.google.cloud.util.bpm.PolicyCache.Hash)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.cloud.util.bpm.PolicyCache.Hash other) {
        if (other == com.google.cloud.util.bpm.PolicyCache.Hash.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getSha256().isEmpty()) {
          sha256_ = other.sha256_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.cloud.util.bpm.PolicyCache.Hash parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.cloud.util.bpm.PolicyCache.Hash) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object sha256_ = "";
      /**
       * <code>string sha256 = 2;</code>
       */
      public java.lang.String getSha256() {
        java.lang.Object ref = sha256_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sha256_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sha256 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSha256Bytes() {
        java.lang.Object ref = sha256_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sha256_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sha256 = 2;</code>
       */
      public Builder setSha256(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sha256_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sha256 = 2;</code>
       */
      public Builder clearSha256() {
        
        sha256_ = getDefaultInstance().getSha256();
        onChanged();
        return this;
      }
      /**
       * <code>string sha256 = 2;</code>
       */
      public Builder setSha256Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sha256_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.util.PolicyCache.Hash)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.util.PolicyCache.Hash)
    private static final com.google.cloud.util.bpm.PolicyCache.Hash DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.cloud.util.bpm.PolicyCache.Hash();
    }

    public static com.google.cloud.util.bpm.PolicyCache.Hash getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hash>
        PARSER = new com.google.protobuf.AbstractParser<Hash>() {
      @java.lang.Override
      public Hash parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hash(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hash> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hash> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.cloud.util.bpm.PolicyCache.Hash getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 1;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int BUCKET_FIELD_NUMBER = 2;
  private static final class BucketDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>newDefaultInstance(
                com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_BucketEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.cloud.util.bpm.PolicyCache.Hash.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> bucket_;
  private com.google.protobuf.MapField<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
  internalGetBucket() {
    if (bucket_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          BucketDefaultEntryHolder.defaultEntry);
    }
    return bucket_;
  }

  public int getBucketCount() {
    return internalGetBucket().getMap().size();
  }
  /**
   * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
   */

  public boolean containsBucket(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetBucket().getMap().containsKey(key);
  }
  /**
   * Use {@link #getBucketMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> getBucket() {
    return getBucketMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
   */

  public java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> getBucketMap() {
    return internalGetBucket().getMap();
  }
  /**
   * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
   */

  public com.google.cloud.util.bpm.PolicyCache.Hash getBucketOrDefault(
      java.lang.String key,
      com.google.cloud.util.bpm.PolicyCache.Hash defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> map =
        internalGetBucket().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
   */

  public com.google.cloud.util.bpm.PolicyCache.Hash getBucketOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> map =
        internalGetBucket().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetBucket(),
        BucketDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    for (java.util.Map.Entry<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> entry
         : internalGetBucket().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
      bucket__ = BucketDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bucket__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.util.bpm.PolicyCache)) {
      return super.equals(obj);
    }
    com.google.cloud.util.bpm.PolicyCache other = (com.google.cloud.util.bpm.PolicyCache) obj;

    boolean result = true;
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && internalGetBucket().equals(
        other.internalGetBucket());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    if (!internalGetBucket().getMap().isEmpty()) {
      hash = (37 * hash) + BUCKET_FIELD_NUMBER;
      hash = (53 * hash) + internalGetBucket().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.util.bpm.PolicyCache parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.util.bpm.PolicyCache prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.util.PolicyCache}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.util.PolicyCache)
      com.google.cloud.util.bpm.PolicyCacheOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetBucket();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableBucket();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.util.bpm.PolicyCache.class, com.google.cloud.util.bpm.PolicyCache.Builder.class);
    }

    // Construct using com.google.cloud.util.bpm.PolicyCache.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      internalGetMutableBucket().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.util.bpm.PolicyCacheProto.internal_static_google_protobuf_util_PolicyCache_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.util.bpm.PolicyCache getDefaultInstanceForType() {
      return com.google.cloud.util.bpm.PolicyCache.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.util.bpm.PolicyCache build() {
      com.google.cloud.util.bpm.PolicyCache result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.util.bpm.PolicyCache buildPartial() {
      com.google.cloud.util.bpm.PolicyCache result = new com.google.cloud.util.bpm.PolicyCache(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.timestamp_ = timestamp_;
      result.bucket_ = internalGetBucket();
      result.bucket_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.util.bpm.PolicyCache) {
        return mergeFrom((com.google.cloud.util.bpm.PolicyCache)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.util.bpm.PolicyCache other) {
      if (other == com.google.cloud.util.bpm.PolicyCache.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      internalGetMutableBucket().mergeFrom(
          other.internalGetBucket());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.util.bpm.PolicyCache parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.util.bpm.PolicyCache) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> bucket_;
    private com.google.protobuf.MapField<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
    internalGetBucket() {
      if (bucket_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BucketDefaultEntryHolder.defaultEntry);
      }
      return bucket_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
    internalGetMutableBucket() {
      onChanged();;
      if (bucket_ == null) {
        bucket_ = com.google.protobuf.MapField.newMapField(
            BucketDefaultEntryHolder.defaultEntry);
      }
      if (!bucket_.isMutable()) {
        bucket_ = bucket_.copy();
      }
      return bucket_;
    }

    public int getBucketCount() {
      return internalGetBucket().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public boolean containsBucket(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetBucket().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBucketMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> getBucket() {
      return getBucketMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> getBucketMap() {
      return internalGetBucket().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public com.google.cloud.util.bpm.PolicyCache.Hash getBucketOrDefault(
        java.lang.String key,
        com.google.cloud.util.bpm.PolicyCache.Hash defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> map =
          internalGetBucket().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public com.google.cloud.util.bpm.PolicyCache.Hash getBucketOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> map =
          internalGetBucket().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearBucket() {
      internalGetMutableBucket().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public Builder removeBucket(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableBucket().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash>
    getMutableBucket() {
      return internalGetMutableBucket().getMutableMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */
    public Builder putBucket(
        java.lang.String key,
        com.google.cloud.util.bpm.PolicyCache.Hash value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableBucket().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .google.protobuf.util.PolicyCache.Hash&gt; bucket = 2;</code>
     */

    public Builder putAllBucket(
        java.util.Map<java.lang.String, com.google.cloud.util.bpm.PolicyCache.Hash> values) {
      internalGetMutableBucket().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.util.PolicyCache)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.util.PolicyCache)
  private static final com.google.cloud.util.bpm.PolicyCache DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.util.bpm.PolicyCache();
  }

  public static com.google.cloud.util.bpm.PolicyCache getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PolicyCache>
      PARSER = new com.google.protobuf.AbstractParser<PolicyCache>() {
    @java.lang.Override
    public PolicyCache parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PolicyCache(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PolicyCache> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PolicyCache> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.util.bpm.PolicyCache getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

